// AUTHENTICATION
export const AUTHENTICATE_STARTED = 'AUTHENTICATE_STARTED'
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR'
export const LOGOUT = 'LOGOUT'
